//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YungChingRehouse_Interview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int accountId { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public bool isAdmin { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string passwordSalt { get; set; }
    }
}
